// Auto-generated by scripts/sync-pen-tokens.mjs. Do not edit manually.

export const PEN_TOKEN_SOURCE = 'design/design-system.pen' as const;
export const PEN_TOKEN_SOURCE_VERSION = "2.8" as const;

export const PEN_THEME_AXES = {
  "Mode": [
    "Light",
    "Dark"
  ],
  "Base": [
    "Neutral",
    "Gray",
    "Stone",
    "Zinc",
    "Slate"
  ],
  "Accent": [
    "Default",
    "Red",
    "Rose",
    "Orange",
    "Green",
    "Blue",
    "Yellow",
    "Violet"
  ]
} as const;

export const PEN_DEFAULT_TOKENS = {
  "--accent": "#f5f5f5",
  "--accent-foreground": "#171717",
  "--background": "#fafafa",
  "--black": "#000000",
  "--border": "#e5e5e5",
  "--card": "#fafafa",
  "--card-foreground": "#0a0a0a",
  "--destructive": "#e7000b",
  "--foreground": "#0a0a0a",
  "--input": "#e5e5e5",
  "--muted": "#f5f5f5",
  "--muted-foreground": "#737373",
  "--popover": "#fafafa",
  "--popover-foreground": "#0a0a0a",
  "--primary": "#171717",
  "--primary-foreground": "#fafafa",
  "--ring": "#a3a3a3",
  "--secondary": "#f5f5f5",
  "--secondary-foreground": "#171717",
  "--sidebar": "#fafafa",
  "--sidebar-accent": "#f4f4f4",
  "--sidebar-accent-foreground": "#18181b",
  "--sidebar-border": "#e4e4e7",
  "--sidebar-foreground": "#09090b",
  "--sidebar-primary": "#18181b",
  "--sidebar-primary-foreground": "#fafafa",
  "--sidebar-ring": "#71717a",
  "--white": "#ffffffff"
} as const;

export type PenTokenName = keyof typeof PEN_DEFAULT_TOKENS;

export function getPenToken(token: PenTokenName): string {
  return PEN_DEFAULT_TOKENS[token];
}
